const icons = {
    right_arrow: require('./src/right-arrow.png'),
    logo: require('./src/logo.png'),
    profile: require('./src/profile.png'),
    at: require('./src/at.png'),
    message: require('./src/message.png'),
    mobile_solid: require('./src/mobile-solid.png'),
    export: require('./src/export.png'),
    lock_solid: require('./src/lock-solid.png'),
    offer: require('./src/offer.png'),
    home: require('./src/home.png'),
    refer: require('./src/refer.png'),
    profile3: require('./src/profile3.png'),
    user_icon: require('./src/user_icon.png'),
    coin_dollar: require('./src/coin_dollar.png'),
    notification_icon: require('./src/notification_icon.png'),
    time_circle : require('./src/time_circle.png'),
    back : require('./src/back.png'),
    cash : require('./src/cash.png'),
    promotion : require('./src/promotion.png'),
    refer_ic : require('./src/refer_ic.png'),
    policy : require('./src/policy.png'),
    terms_and_conditions : require('./src/terms_and_conditions.png'),
    favorite : require('./src/favorite.png'),
    information_desk : require('./src/information_desk.png'),
    logout : require('./src/logout.png'),
    coins : require('./src/coins.png'),
    // batch_processing : require('./src/batch_processing.png'),
    task_list : require('./src/task_list.png'),
    loading : require('./src/loading.gif'),
    money : require('./src/money.png'),
    youtube : require('./src/youtube.png'),
    youtube_shorts : require('./src/youtube_shorts.png'),
    playStore : require('./src/playStore.jpg'),
    insta : require('./src/insta.jpeg'),
    watch_and_earn : require('./src/watch_and_earn.jpeg'),
    spin_and_earn : require('./src/spin_and_earn.jpeg'),
    download : require('./src/download.webp'),
    
}
export default icons